language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - 10
  - 8
matrix:
## An ENOMEM error occurs with 10+ under Travis-CI for Windows.
## Disable until we can determine the cause.
#  include:
#    - os: windows
#      node_js: "latest"
  exclude:
    - os: windows
      node_js: "node"
    - os: windows
      node_js: 10
git:
  depth:
    1
before_script:
  - npm i npm@latest -g
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
